import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js";
const url=Deno.env.get("SUPABASE_URL")!, anonKey=Deno.env.get("SUPABASE_ANON_KEY")!, adminKey=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const admin=createClient(url,adminKey);
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type"};
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...cors,"Content-Type":"application/json"}});
function validGrid(p:string[]){return Array.isArray(p)&&p.length===9&&p.every(r=>typeof r==='string'&&r.length===9&&/^[0-9.]+$/.test(r));}
function countSolutions(rows:string[],limit=2){const a=rows.map(r=>[...r].map(x=>x==='.'||x==='0'?0:Number(x)));let count=0;const ok=(r:number,c:number,n:number)=>{for(let i=0;i<9;i++)if(a[r][i]===n||a[i][c]===n)return false;const br=Math.floor(r/3)*3,bc=Math.floor(c/3)*3;for(let rr=br;rr<br+3;rr++)for(let cc=bc;cc<bc+3;cc++)if(a[rr][cc]===n)return false;return true};const dfs=()=>{if(count>=limit)return;let br=-1,bc=-1,best:number[]|null=null;for(let r=0;r<9;r++)for(let c=0;c<9;c++)if(a[r][c]===0){const cand:number[]=[];for(let n=1;n<=9;n++)if(ok(r,c,n))cand.push(n);if(!cand.length)return;if(!best||cand.length<best.length){best=cand;br=r;bc=c;if(cand.length===1)break}}if(br<0){count++;return}for(const n of best!){a[br][bc]=n;dfs();a[br][bc]=0;if(count>=limit)return}};dfs();return count}
function shuffled<T>(a:T[]){const x=[...a];for(let i=x.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[x[i],x[j]]=[x[j],x[i]]}return x}
function generatePuzzle(difficulty:string){const grid=Array.from({length:9},()=>Array(9).fill(0));const valid=(r:number,c:number,n:number)=>{for(let i=0;i<9;i++)if(grid[r][i]===n||grid[i][c]===n)return false;const br=Math.floor(r/3)*3,bc=Math.floor(c/3)*3;for(let rr=br;rr<br+3;rr++)for(let cc=bc;cc<bc+3;cc++)if(grid[rr][cc]===n)return false;return true};const fill=()=>{let br=-1,bc=-1,best:number[]|null=null;for(let r=0;r<9;r++)for(let c=0;c<9;c++)if(grid[r][c]===0){const cand=shuffled([1,2,3,4,5,6,7,8,9].filter(n=>valid(r,c,n)));if(!cand.length)return false;if(!best||cand.length<best.length){best=cand;br=r;bc=c;if(cand.length===1)break}}if(br<0)return true;for(const n of best!){grid[br][bc]=n;if(fill())return true;grid[br][bc]=0}return false};fill();const target=difficulty==='easy'?40:difficulty==='medium'?32:25;let clues=81;for(const idx of shuffled(Array.from({length:81},(_,i)=>i))){if(clues<=target)break;const r=Math.floor(idx/9),c=idx%9,old=grid[r][c];grid[r][c]=0;const rows=grid.map(row=>row.map(n=>n?String(n):'.').join(''));if(countSolutions(rows)!==1)grid[r][c]=old;else clues--}return grid.map(row=>row.map(n=>n?String(n):'.').join(''))}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});if(req.method!=='POST')return json({error:'POST required'},405);const auth=req.headers.get('Authorization');if(!auth)return json({error:'Authentication required'},401);const userClient=createClient(url,anonKey,{global:{headers:{Authorization:auth}}});const{data:{user},error:userError}=await userClient.auth.getUser();if(userError||!user)return json({error:'Invalid session'},401);try{const body=await req.json();if(body.action==='start'){const difficulty=body.difficulty||'easy',mode=body.mode||'classic';if(!['easy','medium','difficult'].includes(difficulty)||!['classic','daily','speed_run'].includes(mode))return json({error:'Invalid game mode'},400);let puzzle:string[],dailyDate:null|string=null;if(mode==='daily'){dailyDate=new Date().toISOString().slice(0,10);const{data,error}=await admin.from('daily_challenges').select('puzzle,difficulty').eq('challenge_date',dailyDate).eq('difficulty',difficulty).maybeSingle();if(error||!data)return json({error:'Daily challenge unavailable'},404);puzzle=data.puzzle}else puzzle=generatePuzzle(difficulty);if(!validGrid(puzzle)||countSolutions(puzzle)!==1)return json({error:'Server failed to create a valid unique puzzle'},500);const clues=puzzle.join('').replace(/\./g,'').length;const range=difficulty==='easy'?clues>=38:difficulty==='medium'?clues>=28&&clues<=36:clues<=28;if(!range)return json({error:'Generated puzzle does not match difficulty'},500);const{data:session,error:sessionError}=await admin.from('competitive_sessions').insert({user_id:user.id,puzzle,difficulty,mode,daily_date:dailyDate}).select('id,started_at').single();if(sessionError)return json({error:sessionError.message},500);return json({session_id:session.id,started_at:session.started_at,puzzle,difficulty,mode})}if(body.action==='verify'){const{data,error}=await admin.rpc('verify_competitive_session',{p_session_id:body.session_id,p_board:body.board,p_mistakes:0,p_hints_used:0,p_client_score:0});if(error)return json({error:error.message},400);return json(data)}return json({error:'Unknown action'},400)}catch(e){return json({error:e instanceof Error?e.message:'Invalid request'},400)}});
